// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoBibliotecaVirtual.Context;

#nullable disable

namespace ProyectoBibliotecaVirtual.Migrations
{
    [DbContext(typeof(BSD))]
    [Migration("20250821204327_InitBibliotecaVirtual2")]
    partial class InitBibliotecaVirtual2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoBibliotecaVirtual.Models.Administradores", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_NACIMIENTO");

                    b.Property<string>("adminContraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLAVE_ADMIN");

                    b.Property<string>("adminUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("adminUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USER_ADMIN");

                    b.Property<int>("edad")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("ADMIN_EDAD");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_REGISTRO");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ADMIN_TAG");

                    b.HasKey("id");

                    b.ToTable("ADMINISTRADORES");
                });
#pragma warning restore 612, 618
        }
    }
}
